- 5.018.004-64bit,threaded/Dockerfile
- 5.018.004-64bit/Dockerfile
- 5.020.001-64bit,threaded/Dockerfile
- 5.020.001-64bit/Dockerfile
- generate.pl
This is just a PR to get a conversation going.  When I made this change my build reduced by more than 100M.  Is this something that we can do?  Is there a reason to leave the old stuff behind?
> Do more at once to make image smaller

- generate.pl
I tested this on my system with 5.14 and I was able to run generate.pl. It created the expected subdirectories, no warnings or errors.
> Bump down generate.pl version to 5.14

- 5.022.000-64bit,threaded/DevelPatchPerl.patch
- 5.022.000-64bit,threaded/Dockerfile
- 5.022.000-64bit/DevelPatchPerl.patch
- 5.022.000-64bit/Dockerfile
- Releases.yaml
I didn't know whether to include the useless `.patch` files that were generated -- I'm happy to rebase to not include them.
It looks like `generate.pl` is also wanting to bump the `Devel::PatchPerl` version number in all the older versions, which I ignored. :smile:
> Add Perl 5.22!

- generate.pl
Perl's ./Configure can be asked to build a shared library, libperl.so,
which is required by some modules from CPAN (like Imagemagick), or when
you want to embed the Perl interpreter in your own programs.
However, because there may be a performance penalty, the "old" static
builds have not been removed.
More information can be found in the installation manual at
https://metacpan.org/pod/distribution/perl/INSTALL#Building-a-shared-Perl-library
> Add -Duseshrplib to build flags to build a shared libperl.so

- generate.pl
Let `vendorprefix=/usr/local` so `vendorlib` and `vendorarch` can point
to paths in `/usr/local/lib/perl5/vendor_perl`.  Extend the generator.pl
also so we can add more `Configure` settings if we needed it later.
Fixes #32.
> Add vendor paths

- 5.008.009-64bit,threaded/Dockerfile
- 5.008.009-64bit/Dockerfile
- 5.010.001-64bit,threaded/Dockerfile
- 5.010.001-64bit/Dockerfile
- 5.012.005-64bit,threaded/Dockerfile
- 5.012.005-64bit/Dockerfile
- 5.014.004-64bit,threaded/Dockerfile
- 5.014.004-64bit/Dockerfile
- 5.016.003-64bit,threaded/Dockerfile
- 5.016.003-64bit/Dockerfile
- 5.018.004-64bit,threaded/Dockerfile
- 5.018.004-64bit/Dockerfile
- 5.020.003-64bit,threaded/Dockerfile
- 5.020.003-64bit/Dockerfile
- 5.022.004-64bit,threaded/Dockerfile
- 5.022.004-64bit/Dockerfile
- 5.024.002-64bit,threaded/Dockerfile
- 5.024.002-64bit/Dockerfile
- 5.026.000-64bit,threaded/Dockerfile
- 5.026.000-64bit/Dockerfile
- Releases.yaml
- generate.pl
Add a `buildpack-deps` option that lets us specify what tag to use on
building Perl images.  This can then let us build older Perls (<5.20)
against their contemporary build stack.
Fixes #34.
> Use tagged buildpack-deps

- 5.008.009-64bit,threaded/Dockerfile
- 5.008.009-64bit/Dockerfile
- 5.010.001-64bit,threaded/Dockerfile
- 5.010.001-64bit/Dockerfile
- 5.012.005-64bit,threaded/Dockerfile
- 5.012.005-64bit/Dockerfile
- 5.014.004-64bit,threaded/Dockerfile
- 5.014.004-64bit/Dockerfile
- 5.016.003-64bit,threaded/Dockerfile
- 5.016.003-64bit/Dockerfile
- 5.018.004-64bit,threaded/Dockerfile
- 5.018.004-64bit/Dockerfile
- 5.020.003-64bit,threaded/Dockerfile
- 5.020.003-64bit/Dockerfile
- 5.022.004-64bit,threaded/Dockerfile
- 5.022.004-64bit/Dockerfile
- 5.024.002-64bit,threaded/Dockerfile
- 5.024.002-64bit/Dockerfile
- 5.026.000-64bit,threaded/Dockerfile
- 5.026.000-64bit/Dockerfile
- Releases.yaml
- generate.pl
We seem to be using www.cpan.org for getting the Perl tarballs for
patching with Devel::PatchPerl, yet in our generated Dockerfiles we are
using cpan.metacpan.org instead.  Since the former location is listed in
www.perl.org as the canonical Perl source location, let's base from that
as our single source of truth.
This also means we can depend less on finding which PAUSE account has
which Perl release, so let's remove that from the Releases.yaml as well.
> Use canonical url for perl downloads

- 5.008.009-64bit,threaded/Dockerfile
- 5.008.009-64bit/Dockerfile
- 5.010.001-64bit,threaded/Dockerfile
- 5.010.001-64bit/Dockerfile
- 5.012.005-64bit,threaded/Dockerfile
- 5.012.005-64bit/Dockerfile
- 5.014.004-64bit,threaded/Dockerfile
- 5.014.004-64bit/Dockerfile
- 5.016.003-64bit,threaded/Dockerfile
- 5.016.003-64bit/Dockerfile
- 5.018.004-64bit,threaded/Dockerfile
- 5.018.004-64bit/Dockerfile
- 5.020.003-64bit,threaded/Dockerfile
- 5.020.003-64bit/Dockerfile
- 5.022.004-64bit,threaded/Dockerfile
- 5.022.004-64bit/Dockerfile
- 5.024.002-64bit,threaded/Dockerfile
- 5.024.002-64bit/Dockerfile
- 5.026.000-64bit,threaded/Dockerfile
- 5.026.000-64bit/Dockerfile
- generate.pl
Embed a SHA256 checksum (taken from the CPAN author's CHECKSUMS file)
for a specific cpanm version (currently 1.7043) so that we can verify
upon download of the dist tarball.  This effectively makes installing
cpanm in the same fashion as installing Perl itself.
Fixes #39.
> Make cpanm install more secure via checksum

- 5.008.009-64bit,threaded/Dockerfile
- 5.008.009-64bit/Dockerfile
- 5.010.001-64bit,threaded/Dockerfile
- 5.010.001-64bit/Dockerfile
- 5.012.005-64bit,threaded/Dockerfile
- 5.012.005-64bit/Dockerfile
- 5.014.004-64bit,threaded/Dockerfile
- 5.014.004-64bit/Dockerfile
- 5.016.003-64bit,threaded/Dockerfile
- 5.016.003-64bit/Dockerfile
- 5.018.004-64bit,threaded/Dockerfile
- 5.018.004-64bit/Dockerfile
- 5.020.003-64bit,threaded/Dockerfile
- 5.020.003-64bit/Dockerfile
- 5.022.004-64bit,threaded/Dockerfile
- 5.022.004-64bit/Dockerfile
- 5.024.002-64bit,threaded/Dockerfile
- 5.024.002-64bit/Dockerfile
- 5.026.000-64bit,threaded/Dockerfile
- 5.026.000-64bit/Dockerfile
- generate.pl
This builds on https://github.com/Perl/docker-perl/pull/38, and adds an appropriate `-Darchname` value for cross-building (arm32v7 builds on an arm64v8 kernel, i386 builds on an amd64 kernel, etc), and conditionally converts `-Duse64bitall` into `-Duse64bitint` (which is what Debian uses when compiling Perl).
> *** You have chosen a maximally 64-bit build,
> *** but your pointers are only 4 bytes wide.
> *** Please rerun Configure without -Duse64bitall.
> *** Since you have quads, you could possibly try with -Duse64bitint.
See also https://sources.debian.net/src/perl/stretch/debian/config.debian/#L115 and https://sources.debian.net/src/perl/stretch/debian/config.debian/#L130.
> ```
>     -Darchname=$host_gnu_type			\
> ...
>     -Duse64bitint                               \
> ```
I've …
> Adjust "./Configure" for wider architecture support

- generate.pl
When running generate I get a lot of differences in DevelPatchPerl.patch
because git's `diff.mnemonicprefix` is set to `true`. To mitigate this, use `git
diff --src-dir=a/ --dst-dir=b/` so everything is the same as upstream
for everyone.
> Fix bug where git diff always differs with upstream

- .github/workflows/build-image.yml
- .github/workflows/generate-dockerfiles-patches.yml
Implement #68 using the GitHub Actions feature to test both Docker image builds for our Perl images and test the toolchain for generating Dockerfiles/patches.
> Enable CI via GitHub Actions

- 5.026.003-main,threaded-buster/Fix-Time-Local-tests.patch
- 5.026.003-main,threaded-stretch/Fix-Time-Local-tests.patch
- 5.026.003-main-buster/Fix-Time-Local-tests.patch
- 5.026.003-main-stretch/Fix-Time-Local-tests.patch
- 5.026.003-slim,threaded-buster/Fix-Time-Local-tests.patch
- 5.026.003-slim,threaded-stretch/Fix-Time-Local-tests.patch
- 5.026.003-slim-buster/Fix-Time-Local-tests.patch
- 5.026.003-slim-stretch/Fix-Time-Local-tests.patch
- 5.028.002-main,threaded-buster/Fix-Time-Local-tests.patch
- 5.028.002-main,threaded-stretch/Fix-Time-Local-tests.patch
- 5.028.002-main-buster/Fix-Time-Local-tests.patch
- 5.028.002-main-stretch/Fix-Time-Local-tests.patch
- 5.028.002-slim,threaded-buster/Fix-Time-Local-tests.patch
- 5.028.002-slim,threaded-stretch/Fix-Time-Local-tests.patch
- 5.028.002-slim-buster/Fix-Time-Local-tests.patch
- 5.028.002-slim-stretch/Fix-Time-Local-tests.patch
- cpanfile
- generate.pl
Ref. #76 (not quite fixes it for all perls yet, prioritizing 5.28 which is the current supported version affected.)
> Fix Time-Local test failure upon year 2020 for 5.26 - 5.28

- .github/workflows/build-image.yml
- 5.028.003-main,threaded-buster/rt-perl-133295.patch
- 5.028.003-main,threaded-stretch/rt-perl-133295.patch
- 5.028.003-main-buster/rt-perl-133295.patch
- 5.028.003-main-stretch/rt-perl-133295.patch
- 5.028.003-slim,threaded-buster/rt-perl-133295.patch
- 5.028.003-slim,threaded-stretch/rt-perl-133295.patch
- 5.028.003-slim-buster/rt-perl-133295.patch
- 5.028.003-slim-stretch/rt-perl-133295.patch
Builds for 5.28.3 was failing on https://github.com/docker-library/official-images/pull/8122 due to missing `rt-perl-133295.patch` (commit 01044791941b91f99e970c3f1256d9dc0daee5e4 which was in 5.28.2, and something Devel::PatchPerl isn't really responsible for.)  Restore that patch, and try to ensure we build current and previous supported Perls here before taking it to official-images.
> Restore GDBM_File test skip for failing 5.28.3 builds

- library.pl
This accepts an optional `--eol` flag to also include the EOL versions (with a big comment about removing them post-build).
(This is as mentioned/promised in https://github.com/Perl/docker-perl/pull/101#issuecomment-834900590; it's a bit rough, but probably better than continuing to maintain the generated file by hand? :innocent:)
The output ordering/preference is based on the order of things in `config.yml`, so as long as that stays consistent, this should DTRT. :smile:
> Add basic "library.pl" script for generating "library/perl" file

- cpanfile
generate.pl uses LWP::Simple, which is not a core module, so I included it in cpanfile
https://github.com/AnaTofuZ/docker-perl/blob/c02e3bce8af52f3cfb070c376d15f39b657759a2/generate.pl#L7
> add LWP::Simple to cpanfile

- .github/workflows/build-image.yml
- 5.032.001-main,threaded-bullseye/Dockerfile
- 5.032.001-main,threaded-buster/Dockerfile
- 5.032.001-main-bullseye/Dockerfile
- 5.032.001-main-buster/Dockerfile
- 5.032.001-slim,threaded-bullseye/Dockerfile
- 5.032.001-slim,threaded-buster/Dockerfile
- 5.032.001-slim-bullseye/Dockerfile
- 5.032.001-slim-buster/Dockerfile
- 5.034.001-main,threaded-bullseye/Dockerfile
- 5.034.001-main,threaded-buster/Dockerfile
- 5.034.001-main-bullseye/Dockerfile
- 5.034.001-main-buster/Dockerfile
- 5.034.001-slim,threaded-bullseye/Dockerfile
- 5.034.001-slim,threaded-buster/Dockerfile
- 5.034.001-slim-bullseye/Dockerfile
- 5.034.001-slim-buster/Dockerfile
- 5.036.000-main,threaded-bullseye/Dockerfile
- 5.036.000-main,threaded-buster/Dockerfile
- 5.036.000-main-bullseye/Dockerfile
- 5.036.000-main-buster/Dockerfile
- 5.036.000-slim,threaded-bullseye/Dockerfile
- 5.036.000-slim,threaded-buster/Dockerfile
- 5.036.000-slim-bullseye/Dockerfile
- 5.036.000-slim-buster/Dockerfile
- generate.pl
Follow up for #114 - we add `PERL_CPANM_OPT` configuration in the Dockerfile and ensure we have install tools for `cpanm` that can pull over HTTPS.
> Configure cpanm to install over HTTPS

- .github/workflows/build-image.yml
- 5.032.001-main,threaded-bullseye/Dockerfile
- 5.032.001-main,threaded-buster/Dockerfile
- 5.032.001-main-bullseye/Dockerfile
- 5.032.001-main-buster/Dockerfile
- 5.032.001-slim,threaded-bullseye/Dockerfile
- 5.032.001-slim,threaded-buster/Dockerfile
- 5.032.001-slim-bullseye/Dockerfile
- 5.032.001-slim-buster/Dockerfile
- 5.034.001-main,threaded-bullseye/Dockerfile
- 5.034.001-main,threaded-buster/Dockerfile
- 5.034.001-main-bullseye/Dockerfile
- 5.034.001-main-buster/Dockerfile
- 5.034.001-slim,threaded-bullseye/Dockerfile
- 5.034.001-slim,threaded-buster/Dockerfile
- 5.034.001-slim-bullseye/Dockerfile
- 5.034.001-slim-buster/Dockerfile
- 5.036.000-main,threaded-bullseye/Dockerfile
- 5.036.000-main,threaded-buster/Dockerfile
- 5.036.000-main-bullseye/Dockerfile
- 5.036.000-main-buster/Dockerfile
- 5.036.000-slim,threaded-bullseye/Dockerfile
- 5.036.000-slim,threaded-buster/Dockerfile
- 5.036.000-slim-bullseye/Dockerfile
- 5.036.000-slim-buster/Dockerfile
- generate.pl
Reverts Perl/docker-perl#115, fixes #116 - need to revisit other options to fetch and verify CPAN module dists securely in another PR.
> Revert "Configure cpanm to install over HTTPS"

- .github/workflows/build-image.yml
- 5.032.001-main,threaded-bullseye/Dockerfile
- 5.032.001-main,threaded-buster/Dockerfile
- 5.032.001-main-bullseye/Dockerfile
- 5.032.001-main-buster/Dockerfile
- 5.032.001-slim,threaded-bullseye/Dockerfile
- 5.032.001-slim,threaded-buster/Dockerfile
- 5.032.001-slim-bullseye/Dockerfile
- 5.032.001-slim-buster/Dockerfile
- 5.034.001-main,threaded-bullseye/Dockerfile
- 5.034.001-main,threaded-buster/Dockerfile
- 5.034.001-main-bullseye/Dockerfile
- 5.034.001-main-buster/Dockerfile
- 5.034.001-slim,threaded-bullseye/Dockerfile
- 5.034.001-slim,threaded-buster/Dockerfile
- 5.034.001-slim-bullseye/Dockerfile
- 5.034.001-slim-buster/Dockerfile
- 5.036.000-main,threaded-bullseye/Dockerfile
- 5.036.000-main,threaded-buster/Dockerfile
- 5.036.000-main-bullseye/Dockerfile
- 5.036.000-main-buster/Dockerfile
- 5.036.000-slim,threaded-bullseye/Dockerfile
- 5.036.000-slim,threaded-buster/Dockerfile
- 5.036.000-slim-bullseye/Dockerfile
- 5.036.000-slim-buster/Dockerfile
- generate.pl
I was reading domm's blogpost[^1] and domm has some (imo) valid points in using
the slim image and not have SSL support out of the box. Because p5p hasn't made
a decision yet on how to get out of the box SSL support[^2] we are somewhat
left with our own solutions.
Since we now have a discussion about using cpm and we want to use https
endpoints to install packages it would made sense to have the images support
SSL by default as well. This is an attempt to do so.
[^1]: https://domm.plix.at/perl/2022_06_dockerfile_for_perl_5_36.html
[^2]: https://www.nntp.perl.org/group/perl.perl5.porters/2021/11/msg261979.html
The original commit message:
The new Dockerfiles preinstalls IO::Socket::SSL with its dependencies to give
users out of the box SSL support. For slim builds we also keep the …
> Adds out of the box SSL support w/ IO::Socket::SSL

- 5.032.001-main,threaded-bullseye/Dockerfile
- 5.032.001-main,threaded-buster/Dockerfile
- 5.032.001-main-bullseye/Dockerfile
- 5.032.001-main-buster/Dockerfile
- 5.032.001-slim,threaded-bullseye/Dockerfile
- 5.032.001-slim,threaded-buster/Dockerfile
- 5.032.001-slim-bullseye/Dockerfile
- 5.032.001-slim-buster/Dockerfile
- 5.034.001-main,threaded-bullseye/Dockerfile
- 5.034.001-main,threaded-buster/Dockerfile
- 5.034.001-main-bullseye/Dockerfile
- 5.034.001-main-buster/Dockerfile
- 5.034.001-slim,threaded-bullseye/Dockerfile
- 5.034.001-slim,threaded-buster/Dockerfile
- 5.034.001-slim-bullseye/Dockerfile
- 5.034.001-slim-buster/Dockerfile
- 5.036.000-main,threaded-bullseye/Dockerfile
- 5.036.000-main,threaded-buster/Dockerfile
- 5.036.000-main-bullseye/Dockerfile
- 5.036.000-main-buster/Dockerfile
- 5.036.000-slim,threaded-bullseye/Dockerfile
- 5.036.000-slim,threaded-buster/Dockerfile
- 5.036.000-slim-bullseye/Dockerfile
- 5.036.000-slim-buster/Dockerfile
- generate.pl
This adds a prebuilt version of https://metacpan.org/dist/App-cpm as an alternative CPAN module installer with full support for HTTPS sources (among other features such as described in https://metacpan.org/pod/App::cpm::Tutorial.)
Fixes #50.
This also includes a small fix for slim builds on non-x86 archs.
> Add App::cpm and fix slim builds for non-x86{,_64}

- 5.032.001-main,threaded-bullseye/Dockerfile
- 5.032.001-main,threaded-buster/Dockerfile
- 5.032.001-main-bullseye/Dockerfile
- 5.032.001-main-buster/Dockerfile
- 5.032.001-slim,threaded-bullseye/Dockerfile
- 5.032.001-slim,threaded-buster/Dockerfile
- 5.032.001-slim-bullseye/Dockerfile
- 5.032.001-slim-buster/Dockerfile
- 5.034.001-main,threaded-bullseye/Dockerfile
- 5.034.001-main,threaded-buster/Dockerfile
- 5.034.001-main-bullseye/Dockerfile
- 5.034.001-main-buster/Dockerfile
- 5.034.001-slim,threaded-bullseye/Dockerfile
- 5.034.001-slim,threaded-buster/Dockerfile
- 5.034.001-slim-bullseye/Dockerfile
- 5.034.001-slim-buster/Dockerfile
- 5.036.000-main,threaded-bullseye/Dockerfile
- 5.036.000-main,threaded-buster/Dockerfile
- 5.036.000-main-bullseye/Dockerfile
- 5.036.000-main-buster/Dockerfile
- 5.036.000-slim,threaded-bullseye/Dockerfile
- 5.036.000-slim,threaded-buster/Dockerfile
- 5.036.000-slim-bullseye/Dockerfile
- 5.036.000-slim-buster/Dockerfile
- generate.pl
As discussed in https://github.com/docker-library/official-images/pull/12612 :eyes:
(With some other minor updates as I was staring at the code with an open editor - changes along a similar vein :sweat_smile:)
> Add sha256 for "cpm" (and more defensive "curl"/"sha256sum" usage)

- 5.032.001-main,threaded-bullseye/Dockerfile
- 5.032.001-main,threaded-buster/Dockerfile
- 5.032.001-main-bullseye/Dockerfile
- 5.032.001-main-buster/Dockerfile
- 5.032.001-slim,threaded-bullseye/Dockerfile
- 5.032.001-slim,threaded-buster/Dockerfile
- 5.032.001-slim-bullseye/Dockerfile
- 5.032.001-slim-buster/Dockerfile
- 5.034.001-main,threaded-bullseye/Dockerfile
- 5.034.001-main,threaded-buster/Dockerfile
- 5.034.001-main-bullseye/Dockerfile
- 5.034.001-main-buster/Dockerfile
- 5.034.001-slim,threaded-bullseye/Dockerfile
- 5.034.001-slim,threaded-buster/Dockerfile
- 5.034.001-slim-bullseye/Dockerfile
- 5.034.001-slim-buster/Dockerfile
- 5.036.000-main,threaded-bullseye/Dockerfile
- 5.036.000-main,threaded-buster/Dockerfile
- 5.036.000-main-bullseye/Dockerfile
- 5.036.000-main-buster/Dockerfile
- 5.036.000-slim,threaded-bullseye/Dockerfile
- 5.036.000-slim,threaded-buster/Dockerfile
- 5.036.000-slim-bullseye/Dockerfile
- 5.036.000-slim-buster/Dockerfile
- generate.pl
This should fix "cpanm" being mistakenly removed 🙈
I also added some verification of both "cpanm" and "cpm" at least being invokable to help avoid this in the future.
Follow-up to #119 & #120
(See https://github.com/docker-library/official-images/pull/12612#issuecomment-1171780506)
> Adjust "cpm" install to use hard-coded path

- generate.pl
I am using macOS (BSD).
When I run generate.pl, I get the following error.
`tar: Option -a is not permitted in mode -x`
This is because BSD tar does not have the a option. Fortunately, GNU tar works without the a option, so I removed it so that it works with both.
> FIX: tar's a option does not exist in bsd

- .github/workflows/build-image.yml
For more information:
* https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Remove deprecated set-output from workflow

- 5.039.002-main,threaded-bookworm/Dockerfile
- 5.039.002-main,threaded-bullseye/Dockerfile
- 5.039.002-main-bookworm/Dockerfile
- 5.039.002-main-bullseye/Dockerfile
- 5.039.002-slim,threaded-bookworm/Dockerfile
- 5.039.002-slim,threaded-bullseye/Dockerfile
- 5.039.002-slim-bookworm/Dockerfile
- 5.039.002-slim-bullseye/Dockerfile
- config.yml
- https://www.nntp.perl.org/group/perl.perl5.porters/2023/08/msg266915.html
> perldevel: 5.39.1 -> 5.39.2

- library.pl
Debian Bullseye and beyond supports more archs than Buster, so set as the default when building the library manifest for official-images.
Fix for #145.
> library.pl: Fix build archs and set defaults

- .github/workflows/build-image.yml
- generate.pl
This commit patches out insecure http endpoints from the fatpacked `bin/cpanm` executable
Tested with:
- `cpanm Plack@0.9990` (backpan)
- `cpanm Crypt::Argon2@0.024` (TRIAL)
- `cpanm Mojolicious`
Cc: @zakame @dgl @garu
> [CVE-2024-45321] generate: hotpatch bin/cpanm to use HTTPS endpoints

- library.pl
mips64le no longer listed in https://www.debian.org/News/2025/20250809
> library.pl: drop mips64le, add riscv64 for trixie
